#!/bin/sh
dir='/cygdrive/j/FTP/Delicious Agony/Library'
winamp_dir='J:/FTP/Delicious Agony/Library'
playlist_dir='/cygdrive/j/FTP/Delicious Agony/Default Stream/New'
if [ "x$1" = "xy" ]
then
	ignore_dir="y"
	shift
fi
tn=$4
if [ "$1x" = "x" ]
then
        artist=`pwd | sed 's#/[^/]*$##' | awk -F'/' '{print $NF}'`
else
        artist=$1
fi
if [ "$2x" = "x" -a "$3x" = "x" ]
then
        year=`pwd | awk -F'/' '{print $NF}' | awk -F' - ' '{print $1}'`
        album=`pwd | awk -F'/' '{print $NF}' | awk -F' - ' '{print $2}'`
else
        album=$2
        year=$3
fi
if [ "x$1" = "x-" ]
then
        artist=`pwd | awk -F'/' '{print $NF}' | awk -F' - ' '{print $1}'`
        album=`pwd | awk -F'/' '{print $NF}' | awk -F' - ' '{print $2}'`
	if [ "$2x" = "x" ]
	then
		year=`id3v2 -l *01* | grep TYE | awk '{print $NF}'`
		if [ "x$year" = "x" ]
		then
			echo "No 01 file - no year found!"
			exit
		fi
	else
		year=$2
	fi
	tn=$3
fi
if [ "x$1" = "xps" ]
then
        artist=`pwd | awk -F'/' '{print $NF}' | awk -F' - ' '{print $1}'`
        album=`pwd | awk -F'/' '{print $NF}' | awk -F' - ' '{print $2}' | sed 's/ (.*//'`
        year=`pwd | awk -F'/' '{print $NF}' | awk -F'(' '{print $NF}' | sed 's/).*//'`
fi
artist=`~/capitalize "$artist"`
album=`~/capitalize "$album"`
echo "Album: $artist - $album - $year"
newdir="$dir/$artist/$year - $album"
playlist_file="$playlist_dir/$artist - $album.m3u"
new_winamp_dir="$winamp_dir/$artist/$year - $album"
# echo "$playlist_file"
if [ "x$ignore_dir" = "x" -a -d "$newdir" ]
then
	echo "$newdir already exists!"
	exit
fi
mkdir -p "$newdir"

for i in *3
do
	if [ "$4x" = "yx" ]
	then
		echo Track for $i
		read tn
	else
		tn=`perl -e 'print sprintf(q{%02d}, ++$ARGV[0]+$ARGV[1]);' $tn`
	fi
	name=`echo $i | sed -e 's/ from the.*//' -e 's/_/ /g' -e 's/^.* - //' -e 's/.mp3//i'`
	name=`perl -e '$n = $ARGV[0]; $n =~ s/([^\w\047][a-z])/uc($1)/ge; print ucfirst($n);' "$name"`
        name=`echo $name | sed -e 's/ii/II/ig' -e 's/iii/III/ig' -e 's/iv\./IV./ig'`
	trackname=$name
	name=`echo $name | sed -e 's/--/-/g' -e 's/%/-/g'`
	trackname=`echo $trackname | sed -e 's/--/\//g' -e 's/-$/?/' -e 's/- /: /g' -e 's/%/-/g'`
	album=`echo $album | sed -e 's/--/\//g' -e 's/-$/?/' -e 's/- /: /g' -e 's/%/-/g'`
	name=`~/capitalize "$name"`
	trackname=`~/capitalize "$trackname"`
	id3v2 -D "$i"
	id3v2 -A "$album" -a "$artist" -g 92 -T $tn -t "$trackname" -y $year "$i"
	mv "$i" "$newdir/$tn. $name.mp3"
	#winamp_file_name=`echo "$new_winamp_dir/$tn. $name.mp3" | sed 's#/#\\#g'`
	echo Moved to "$newdir/$tn. $name.mp3"
	#echo $winamp_file_name
done
id3v2 -l "$newdir/"*3 | grep TIT2
